language: python
cache: pip
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements.txt
- pip install -e .
script:
- pytest
deploy:
  provider: pypi
  user: pstjohn
  password:
    secure: Lh352v9p09v4B2mANvcOnIrjO/lFZby4AleLzo8XTcI/LRX2qkZwAx1qXfYKzrSFWJGw8jJB2wtnWDWZpLKqWN8rCWm/teqCNjFEcFzppbpRKELrYU60GCg+8m9Hibf5CErsID3yFqpgtMGls0c1zK/v7W4p4LetO9ae6zfjE9vcWcO/7ux7TposK/8A9n5vcRhJdiIlQgzrBr9Ll1bQD4ng37LR7MSFzjMdmif0UwpcTt7AEojAY9n+jN9noX24TSsBrR5gcPp2mHXQMZ9flcJu9wFxFOsRRbhag73Fn0Y3RPEGdCBpleZRfeEUP5BkCn9vFjrQ1jjkMg1fxfDPhGabV1/PjKSqdXQ7tbb+km1UeV6DnnL4WgH9h/dY2+31saJsIWUkcrqkVERkP0v4/dC28soBWG0TIIEGahNTpua5gz4F9zlVWXa/gDbo4Wtcv0M8PJmUPkp978tOgMcoIuko65UcL9BKBDSMIuTp9x0/6/O2BRtMg7r6MYwxkdXKwkKot+ISMaC2f6JPwUnamUh4ipCKVuCx94xpoUbxz2x5i3cpBoFapmWkWoA0QYBx1WUHApa3YQkPpfXzWAgZUHzVzw0eE0RxeNJiygLQKeK9rN+hm3pmoCk7eyOeRJOcElcHQfn1w5wxHzgovOftLsijfv1cTO0UEksHFdmJDrY=
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = 3*
