language: python
cache: pip
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements.txt
- pip install -e .
script:
- pytest
deploy:
  provider: pypi
  user: pstjohn
  password:
    secure: KYQXxopTFFq49zmu3Jsqo1kWMLXfhV2TDNHlZwQvI/axh9HRhvPAZTVZevQtAEcQbcaKalawB5Gd3QEa7AxFBWOYeMHXGh0DRlv3WV9rL1vQv5ujFOiGXEGYorpBzQZNr7+j1FFNeWCMQ7aiVUJjHg3ckpXVM3JZK/qX6AssFXHsxK0ncVQYRK0PwXKiuS3nUQ5opg/3D7fg/Z7bSnAiAk8D7YpwWNe4PLTWtLjzp2qjt0yj9GMNO1HymZFGukfmCsdcoVAqk3wi3+pMMYEJj1gyjlkOlpZDBZ+OIGqR9XyPbiZazAvUBZ6O53LgDFYLJfpyBxRpgmkjbEJCxsNasmPYEDWD/Lk+tLYrs7QhSKHTbS4n3FP424GsVPOZ6O5S2AADSJkhA/UaKZ/B1vmpTYsnB5AR1URJmXKtAw2gYWrwK2ojteMqEepaDuSHbg3MY7fKugeshd+rcWEyCcemvq1TrAhAdCXlfE64lwX9HYvDtRq0qeWV3EkjZhGVG1axoFZlYWMNiZpAf5OsZSQwNwwYQa/mVEhXBzlp2EFfzj0BXhgbqu0CoN1euGRfhEJSBz8tpu+KWxwp/Q5PyhMeYEkVnLpdIN00liUkLCIQZwk299maD5DoTMTYwcxmPCfqPcBi4uNuiW90FdcrCMeZSXLVZcBdAzIDT27Y9uzBurM=
  on:
    tags: true
