language: python
cache: pip
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements.txt
- pip install -e .
script:
- pytest
deploy:
  provider: pypi
  user: pstjohn
  password:
    secure: VudX27zFVJXtbdtKPOp2KEUKQ4LgeB7tQWFLhlNtmU90JrpBbZfc7bDLu7mYD2p6qqCcyEUc9nitGt6aexlgck0OXtGyVZ4TIhL6IfT02L26YgmVDoAZ1pOxkXVLRnq8llTNUMZ4QdO7jvV+vMPtDSpSjWqaeRV/DstE8U2yXnLsYMK+6pI4oyYAlE0opgrA6z920RG2LKLwKc9u07bkQ5jVL3VyFnn7mni3iV3bcooJR8oYWa0gknaKGFNFMvDlk3dVO+cR92ZF04dTKxpkP7Qg013Edy0vTFp6WrP5VOUMn1G1r9aSoSv01+IsgzJdKpxOHPPDY6niMz9hFCB+pH/numjwF3QxMECxcCrScf54g0kG33m2Z/37AjdYwU//eEUJihBXG7lg8yyF7wb6vdp3iSU2vyi82E58l6r5Qu/vQowsnnICFwnAniBBEIY0Az5kZB/ivGBuYBJenB0HZQW6a7e1/v8KYyJiWjjqHHTZBbJ2f6BE7Oi1CHof6z2+ZOuqAud3m0CzDLYZyN8RueGAyBt0xmUFnXJMuoj0J/Knmyu70ybTNEXrvbDhmrrquiNF9PUcMoU59rjnDWCxW79WYDh6ixaydBCkP33NMdtyye6OTANqBOvzK0tX8cGZTN4piX+gRG7cxmhzaTCdn3AXyX5U++UrOduxCEriJ6k=
  on:
    tags: true
