language: python
cache: pip
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements.txt
- pip install -e .
script:
- pytest
deploy:
  provider: pypi
  user: pstjohn
  password:
    secure: daoQaUv19DFeSyCr6v6K6tFr4VWAZFnZxrvD4+E1qH2jSSN8xNlP58twjvniF+ZVSd5M3CKYRw257I8TU23VJVWsaPdgrVbSyDuhd5L5+TIgqj0sILqxvX+2Le2bbP4hHTNS4UR0cCl3olCndgPOz93X2PHpu6dHMwJ3tg5zCUdFNJ9XqFBXvWEHFFqKkYCzmUiwyJIuwjIdD9Ba5p1FaexW/QSdjN4n25E40Xp9H1OAyR5DreUJkEpoRhxZqw81o57RUOD55K8FF+mJgBKDZFhbVGJASO2G81pPJUzKBWw3z/9LURQ0GkNJjqqGLIzrTU7a+L4bqfB3+IGggiE3n+h7eC0GFY01ney/pu1k/KBhpfaMp1PFkIXbe9TKzE6t7vgbXVc+wA6w+ZLXXzGGiMVaUQr5DmtjL3yGfiSE0XXavU7ruddkN2YqPQ3XMsSEXLirB2SfLVLfwB3FCu6u3KoPEm4PIsDLERxHhW5dDudXIkgF6XJNy1n5IzbMlpEzKNJC207inZz1T6RFX/F1Xznhe3xasa5oGKDRczOysTtIOy+IKRznfoihswiM5dLiNbfAb1dfgG/5WD90++bXWpZsyQNSeai/mYxJixk5w7ud+vejS9alg2EADkD+EZ6m6kE63NFz0nqdyjPNNVVWitVnJh+B6es4RbIq7uzyC8M=
  on:
    tags: True
