language: python
cache: pip
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements.txt
- pip install -e .
script:
- pytest
deploy:
  provider: pypi
  user: pstjohn
  password:
    secure: iwOe9qj1hj59oSqBJKXqjuCUx1L5OrqtoWUpY07n2+/1WZ3xLGUrNh1EY/YrO7t3mdPBP3GR4icide3cV9/Fwfg7XYza0VDNnPBjbdwwQE+5BIXdeuQQTIAV32SODH/BG8iUxbyXNl0lYM3Y+IKuS22MkhMfT+3V9Rsk4T2JOdzss0tLijr0RHbJWmtydHe5iRoMBRFu0nJruHnaAKb+xaUfGJSBqtiuEoHZdo5nL4UsDBL18UGw3ckPKz4sSvoi8B9Ofg4M3Tf0dOyOx/+1ALOCxyL7baznk1rY8yMEZyoxhJUDOt70YrHNwFF12zfZYPQS0pgkOFMp29rzg69qL4rj/KR4w9BLNXOiGHPsEqZX/rQFkxxB6wOVOtSnauY3ruMiicO6Zc7XrArlcJYc1pPSEK2rET+dfjZjRi0uAYbrFX+mUgL6PzJnnT+l654rUhrVVg7uD/7aMhi7LcKMZ+TxKcDxFty2Xd6srFrLHD15FcbOFB2P5Ly2Jjpl6+XUaSlz2i1IvRDW5Sg754UqdmfwtjwtAUqPA8z3Zup3GHeYyS9cfUPyoiral1tlI7nqEJG0Mev87KX+zb4IJRp2PwFukRcNeXiCsMxqfUkBtt9pCu3eev0Lw73JKoFRgkOjUZgLZSlVheq2dQLLQR2fWfYCjmuK/0EpwbpUZOZ0GlA=
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = 3*
