language: python
cache: pip
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements.txt
- pip install -e .
script:
- pytest
deploy:
  provider: pypi
  user: pstjohn
  password:
    secure: H5vCV4gX8UOrBlN7vI70m8xEextiVfKKIQvxMBoMIb8aObcOmZeNER46n65GW2xUJTYPoFwjV/OJ42lBrJnAAaNeiieY6UCrafAgLOzdz04Kpvae6vcUr23wlims4CqGr+AJSrzpWqB/k0gLenJIqS6e9oNrU5f30ouP0OGPs0j95vX2B3wtjNZceBU30eYWGiRR9w7SSmd6+1DbyKMEuOm8MO1czv01GdCsXGyf1WjsU72vANDxtSx8CSuX1RzqXkHcwdr7ld7qDhY1alkbZtBacC1FX8xe+urGW01FppqTUbFHZcZZcoM89Vxo4d/IMEienxLL5B6CRROi9lHwSaLKXx0Q+3wkWdtzTlwQoVNK70V4TOL1Yxy9JI+chTz7Ifw2krIhTDQpOCF3aZ8PdIX7UgKhontp4C1zbS9ol2DIND6KRdWM69yvzPoxRGTVRIa9bDDvSHTLm3IdS68RdQCu2w+hTxu6PvHY7EQqLABuQmWtAkc0a3W5yK4fbNfYcwqj/Pn3SXjZr46WwJYvV89rPrs3dHnhpt3dg1euu4wMlZ2bB7yHkn8gZQyYXCciGDjWTpoNrFjyayY0if9AczwyRMxjFsPBrgTKPQyPZJKoMfGNCp17dLT8V5EPi5JWptskIiwpOCAZ/dnBk6bbz8ovMav5SMps8ksYcSgSBtc=
  on:
    tags: true
